import React,{useEffect,useState} from 'react';

const dateLabel=d=>new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const sentLabel=d=>d?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'}).format(new Date(d)):'Unknown';

export default function Followups({calendar,workspace,search,api,refresh,notice,openAccount,focus}){
 const all=[...(calendar?.followups||[]),...(calendar?.followup_skips||[])].filter(d=>workspace==='all'||d.engine===workspace).map(d=>d.external_schedule?.contact_id===d.contact_id?{...d,status:'scheduled',disposition:'SCHEDULED IN GMAIL',body:d.external_schedule.body||'',subject:d.external_schedule.subject||d.subject,word_count:d.external_schedule.body?.split(/\s+/).length||0,thread_url:d.external_schedule.source,why:'Already scheduled by you. Open the thread to review or change the scheduled message.'}:d);
 const dates=[...new Set(all.map(d=>d.day))].sort();
 const[day,setDay]=useState(''),[filter,setFilter]=useState('review'),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(focus){setDay(focus.day);setFilter('all');setSelected(focus.id)}},[focus?.id]);
 const activeDay=day||dates.find(d=>d>=calendar?.today)||dates.at(-1)||calendar?.today;
 const dated=all.filter(d=>d.day===activeDay);
 const cohort=(calendar?.followup_batches||[]).find(b=>b.day===activeDay&&(workspace==='all'||b.engine===workspace));
 const visible=dated.filter(d=>(filter==='all'||d.status===filter)&&(!search||`${d.name} ${d.company} ${d.email} ${d.subject}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>a.company.localeCompare(b.company)||a.name.localeCompare(b.name));
 const current=visible.find(d=>d.id===selected)||visible[0];
 const index=visible.indexOf(current);
 useEffect(()=>{if(current&&selected!==current.id)setSelected(current.id)},[current?.id]);
 const copy=text=>navigator.clipboard.writeText(text).then(()=>notice('Draft copied.')).catch(()=>notice('Clipboard unavailable. Select the draft text to copy it.'));
 async function hold(){setBusy(true);try{await api('/api/calendar',{operation:'followup_status',contact_id:current.contact_id,review_on:current.day,version:current.updated_at,status:current.status==='held'?'review':'held'});await refresh();notice(current.status==='held'?'Primary contact selected. Other contacts at this company are held.':'Draft held.')}catch(e){notice(e.message)}finally{setBusy(false)}}
 return <section className="followups">
  <div className="followup-heading"><div><h2>{activeDay?dateLabel(activeDay):'Follow-ups'}</h2><p>Complete replies to your earlier emails · local drafts</p></div><button className="button secondary" onClick={refresh}>Refresh</button></div>
  <div className="followup-toolbar"><label>Review date <input aria-label="Follow-up review date" type="date" value={activeDay||''} onChange={e=>setDay(e.target.value)}/></label><div className="followup-tabs" role="group" aria-label="Follow-up status">{[['review','Needs review'],['scheduled','Scheduled'],['held','Hold'],['skipped','Skip'],['all','All']].map(([value,label])=><button key={value} aria-pressed={filter===value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}>{label} <span>{dated.filter(d=>value==='all'||d.status===value).length}</span></button>)}</div><span>{new Set(dated.filter(d=>d.status==='review').map(d=>d.account_key)).size} companies to review</span></div>
  <details className="followup-help"><summary>{cohort?`${cohort.cohort} · ${cohort.cohort_count} people · ${cohort.excluded.length} closed`:'About these drafts'}</summary><p className="followup-note">One primary follow-up per company. Alternatives are held; choosing a different primary holds the previous person. These are editorial recommendations, not send approvals. Recheck the thread before sending.</p>{cohort?.excluded?.length>0&&<p className="followup-note">Closed after a reply: {cohort.excluded.map(x=>`${x.name} (${x.company})`).join('; ')}.</p>}</details>
  {visible.length?<div className="followup-layout"><nav className="followup-list" aria-label="Follow-up recipients">{visible.map(d=><button key={d.id} aria-current={current?.id===d.id?'true':undefined} className={current?.id===d.id?'selected':''} onClick={()=>setSelected(d.id)}><strong>{d.name}<small>{d.disposition==='PRIMARY FOLLOW-UP'?'Primary':d.disposition}</small></strong><span>{d.company}</span><span>{d.subject}</span>{d.external_schedule?<em>Scheduled in Gmail: {d.external_schedule.name}</em>:d.other_contacts.length>0&&<em>{d.status==='review'?'Other contact held':`Primary: ${d.primary_name||'Not selected'}`}</em>}</button>)}</nav>
   <article className="followup-reader" key={current.id}><header><div><span className="eyebrow">FOLLOW-UP · {index+1} OF {visible.length}</span><h2>{current.name}</h2><p>{current.role} · {current.company}</p></div><div className="followup-paging"><button aria-label="Previous draft" disabled={index===0} onClick={()=>setSelected(visible[index-1].id)}>←</button><button aria-label="Next draft" disabled={index===visible.length-1} onClick={()=>setSelected(visible[index+1].id)}>→</button></div></header>
    <div className="followup-meta"><span>To: {current.email}</span><span>From: {current.sender_mailbox}</span><span>Last sent: {sentLabel(current.last_outbound_at)} · London time</span></div>
    <p className={current.status==='review'?'followup-account-note':'followup-hold'}><strong>{current.disposition}</strong>{current.body&&` · ${current.word_count} words`}<br/>{current.why}</p>
    {current.external_schedule&&<p className="followup-note">Gmail follow-up: {current.external_schedule.name} · {current.external_schedule.scheduled_display}. {current.status==='scheduled'?(current.body?'The message below was captured from Gmail.':'Open Gmail for the final message.'):'The text below is a local draft; a coworker already has a scheduled follow-up.'} <a href={current.external_schedule.source} target="_blank" rel="noreferrer">View scheduled thread ↗</a></p>}
    {current.body?<><h3>Re: {current.subject.replace(/^Re:\s*/i,'')}</h3><div className="email-body">{current.body}</div></>:<p>{current.status==='scheduled'?'The scheduled message is in Gmail. The older local draft is not displayed as the final version.':'No draft. This conversation is closed.'}</p>}
    <div className="followup-actions">{current.body&&<><button className="button" onClick={()=>copy(current.body)}>Copy {current.status==='scheduled'?'message':'reply'}</button><button className="button secondary" onClick={()=>copy(`To: ${current.email}\nSubject: Re: ${current.subject.replace(/^Re:\s*/i,'')}\n\n${current.body}`)}>Copy with details</button></>}{current.thread_url&&<a className="button secondary" href={current.thread_url} target="_blank" rel="noreferrer">Open Gmail thread ↗</a>}{!['skipped','scheduled'].includes(current.status)&&<button className="text-button" disabled={busy||!!current.lint_issues?.length||!!current.external_schedule} onClick={hold}>{current.status==='held'?'Make primary':'Hold'}</button>}</div>
    <details className="followup-original"><summary>Original email · {current.last_sent_subject}</summary><div className="email-body">{current.last_sent_body||'Open the Gmail thread to read the original email.'}</div></details>
    <button className="text-button" onClick={()=>openAccount(current)}>Open account and research ↗</button>
   </article></div>:<div className="calendar-empty">No {filter==='all'?'':filter==='held'?'held ':'review '}follow-up drafts for this date{search?' matching your search':''}.</div>}
 </section>;
}
