import React,{useEffect,useMemo,useRef,useState} from 'react';
import Followups from './followups.jsx';
import Calendar from './calendar.jsx';
import * as Dialog from '@radix-ui/react-dialog';

const workspaces={technical_contract:'Contract Work',wapahki_facility:'Wapahki',outagehub_api:'OutageHub'};
const statusLabels={all:'All contacts',reply:'Needs reply',followup:'Follow up',draft:'Drafts',write:'To write',scheduled:'Scheduled',waiting:'Waiting',research:'Find email',held:'On hold',closed:'Closed'};
const clean=s=>String(s||'').replaceAll('_',' ');
const fullId=(c,a,p)=>`${c.id}/${a.id}/${p.id}`;
const safeURL=s=>/^https?:\/\//.test(s||'')?s:null;
const date=s=>s?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'Europe/London'}).format(new Date(s)):'—';
async function api(path,value){const r=await fetch(path,value?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}:{});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}

function contactStatus(p,q,f){
 const state=p.state?.status;
 if(['DECLINED','UNSUBSCRIBED','BOUNCED','COMPLETE'].includes(state))return {key:'closed',action:clean(p.state?.reply_type||state).toLowerCase()};
 if(state==='REPLIED')return {key:'reply',action:'Read the response in Gmail'};
 if(q?.status==='cancel_required')return {key:'held',action:'Reconcile the existing Gmail schedule'};
 if(q?.status==='gmail_scheduled'||p.draft_status==='gmail_scheduled')return {key:'scheduled',action:`Scheduled ${date(q?.send_at||p.schedule?.recommended_send_utc)}`};
 if(f?.external_schedule){const own=f.external_schedule.contact_id===f.contact_id;return {key:own?'scheduled':'held',action:own?'Follow-up scheduled in Gmail':`${f.external_schedule.name} already scheduled`};}
 if(f?.status==='review')return {key:'followup',action:`Review follow-up · ${date(f.day+'T12:00:00Z')}`};
 if(f?.status==='held'||p.draft_status==='held')return {key:'held',action:f?.primary_name?`Primary contact: ${f.primary_name}`:'Held for review'};
 if(p.state?.touch_number>0||p.draft_status==='sent')return {key:'waiting',action:p.state?.next_action_at?`Check back ${date(p.state.next_action_at)}`:'Awaiting a response'};
 if(['skipped','excluded'].includes(p.draft_status))return {key:'held',action:'Not selected for outreach'};
 if(!p.email||!['verified','user_supplied'].includes(p.email_status))return {key:'research',action:'Verify a work email'};
 if(p.body)return {key:'draft',action:p.has_local_revision?'Review local revision':'Review first email'};
 return {key:'write',action:'Write first email'};
}

function ContactReader({row,Email,refresh,notice,onFollowup,onChoose}){
 const[editing,setEditing]=useState(false);
 useEffect(()=>setEditing(false),[row?.id]);
 if(!row)return <div className="crm-reader-empty"><span>↖</span><h2>Select a contact</h2><p>The email, company context and next step will appear here.</p></div>;
 const{p,a,c,q,f,status}=row;
 const latest=p.sent_messages?.at(-1);
 const ownSchedule=f?.external_schedule?.contact_id===f?.contact_id&&f?.external_schedule;
 const draft=ownSchedule?{body:ownSchedule.body||'',subject:ownSchedule.subject||f.subject,kind:'Scheduled message · captured from Gmail'}:f?.body?{body:f.body,subject:f.subject,kind:'Local follow-up draft'}:p.state?.touch_number>0||p.draft_status==='sent'?{body:latest?.body||p.sent_record?.body,subject:latest?.subject||p.sent_record?.subject,kind:'Last sent email'}:{body:p.body,subject:p.subject,kind:p.has_local_revision?'Local revision':'First email draft'};
 const thread=(ownSchedule?.source)||f?.thread_url||f?.external_schedule?.source||p.thread_check?.thread_url||safeURL(latest?.source)||(p.state?.thread_id?`https://mail.google.com/mail/u/0/#all/${encodeURIComponent(p.state.thread_id)}`:p.email?`https://mail.google.com/mail/u/0/#search/${encodeURIComponent('in:anywhere '+p.email)}`:null);
 const copy=text=>navigator.clipboard.writeText(text).then(()=>notice('Copied.')).catch(()=>notice('Clipboard unavailable. Select the text to copy it.'));
 const peers=a.contacts.filter(x=>x.id!==p.id);
 return <article className="crm-contact-reader">
  <header className="crm-person-header"><div className="crm-avatar">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h2>{p.name}</h2><p>{p.role}</p><span>{a.name}</span></div><span className={'crm-status '+status.key}>{statusLabels[status.key]}</span></header>
  <div className="crm-address"><span>{p.email||'Work email not verified'}</span>{p.email&&<button aria-label="Copy email address" onClick={()=>copy(p.email)}>Copy</button>}<small>{p.email_status==='verified'?'Verified work email':clean(p.email_status)}</small></div>
  <div className="crm-next"><div><small>NEXT STEP</small><strong>{status.action}</strong></div>{thread&&<a className="button secondary" href={thread} target="_blank" rel="noreferrer">Open Gmail ↗</a>}</div>
  {draft.body?<section className="crm-message"><div className="crm-section-heading"><h3>{draft.kind}</h3><div><button className="text-button" onClick={()=>copy(draft.body)}>Copy email</button>{f?.body?<button className="text-button" onClick={()=>onFollowup(row)}>Review follow-up →</button>:status.key==='draft'&&<button className="text-button" onClick={()=>setEditing(!editing)}>{editing?'Close editor':'Edit & review'}</button>}</div></div>{f?.external_schedule&&<p className="crm-inline-note">{ownSchedule?'This message is already scheduled in Gmail.':'A coworker has a follow-up scheduled in Gmail. This is a local draft.'}</p>}{editing?<Email p={p} campaign={c} account={a} refresh={refresh} notice={notice}/>:<><h4>{draft.subject}</h4><div className="crm-email-body">{draft.body}</div></>}</section>:<section className="crm-message crm-not-written"><h3>{status.key==='research'?'Contact research needed':status.key==='reply'?'Reply received':status.key==='scheduled'?'Scheduled in Gmail':status.key==='closed'?'Conversation closed':p.state?.touch_number>0?'Conversation in progress':'Ready for a first email'}</h3><p>{status.key==='research'?'The person is identified, but their work email still needs verification.':status.key==='reply'?'Open Gmail to read the response and continue the conversation.':status.key==='scheduled'?'Open the scheduled thread in Gmail to read your final message.':status.key==='closed'?'No further outreach is planned for this contact.':p.state?.touch_number>0?'The exact sent message is not captured here. Open Gmail to read the conversation.':'The company and contact are researched. No email has been written for this contact yet.'}</p>{!p.state?.touch_number&&a.opportunity?.next_step&&<p><strong>Possible opening:</strong> {a.opportunity.next_step}</p>}</section>}
  <section className="crm-context"><h3>Why this contact</h3><p>{p.reason||'No selection note recorded.'}</p><h3>Why this company</h3><p>{a.qualification?.reason||a.strategy?.central_reason||'Research pending.'}</p>{a.opportunity?.buyer_grade&&<div className="crm-buyer"><strong>Buying evidence</strong><span>{a.opportunity.buyer_grade}</span></div>}
   {a.hypotheses?.length>0&&<><h3>Possible work <small>To confirm with the team</small></h3>{a.hypotheses.slice(0,2).map((h,i)=><p key={i}>{h.statement}</p>)}</>}
   {peers.length>0&&<details><summary>{peers.length} other {peers.length===1?'contact':'contacts'} at {a.name}</summary>{peers.map(person=><button className="crm-peer" key={person.id} onClick={()=>onChoose(fullId(c,a,person))}><strong>{person.name}</strong><span>{person.role}</span></button>)}</details>}
   <details><summary>Research & sources · {a.facts?.length||0} findings</summary>{(a.facts||[]).map(fact=><div className="crm-fact" key={fact.id}><p>{fact.text}</p>{fact.sources.map(id=>{const s=a.sources.find(x=>x.id===id);return safeURL(s?.url)?<a key={id} href={s.url} target="_blank" rel="noreferrer">{new URL(s.url).hostname.replace('www.','')} ↗</a>:null})}</div>)}</details>
   <details><summary>History & batch</summary><p>{c.name}</p><p>Last sent: {date(p.state?.last_outbound_at)} · {p.state?.touch_number||0} recorded touches</p><p>{p.thread_check?.observation||p.thread_check?.scope_limit||'Mailbox coverage not recorded.'}</p>{(p.sent_messages||[]).map((m,i)=><div className="crm-fact" key={i}><strong>{m.subject}</strong><p>{date(m.at)}</p><div className="crm-email-body">{m.body}</div></div>)}</details>
  </section>
 </article>;
}

export default function Workspace({Email}){
 const initial=useRef(location.hash.slice(1).split('/'));
 const[workspace,setWorkspace]=useState('technical_contract'),[view,setView]=useState(initial.current[0]==='followups'?'followups':initial.current[0]==='schedule'?'calendar':'contacts'),[data,setData]=useState(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState(initial.current[0]==='inbox'?'reply':initial.current[0]==='drafts'?'draft':'all'),[batch,setBatch]=useState(['drafts','contacts'].includes(initial.current[0])&&initial.current[1]?decodeURIComponent(initial.current[1]):'all'),[selected,setSelected]=useState(initial.current[0]==='account'?initial.current.slice(1,4).join('/'):'') ,[allPeople,setAllPeople]=useState(false),[sort,setSort]=useState('priority'),[toast,setToast]=useState(''),[missionOpen,setMissionOpen]=useState(false),[goal,setGoal]=useState(''),[saving,setSaving]=useState(false),[followupFocus,setFollowupFocus]=useState(null);
 const searchRef=useRef(null);
 const refresh=async()=>{try{const next=await api('/api/campaigns');setData(next);setError('');return next;}catch(e){setError(e.message)}};
 useEffect(()=>{refresh();const id=setInterval(refresh,15000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(id)}},[toast]);
 useEffect(()=>{const listener=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus()}if(e.key==='Escape')setMissionOpen(false)};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[]);
 useEffect(()=>{if(data&&['account','contacts','drafts'].includes(initial.current[0])&&initial.current[1]){const c=data.campaigns.find(x=>x.id===initial.current[1]);if(c)setWorkspace(c.engine);if(initial.current[0]==='account')setAllPeople(true);initial.current=[]}},[!!data]);
 const campaigns=(data?.campaigns||[]).filter(c=>c.engine===workspace);
 const rows=useMemo(()=>{
  const queue=new Map((data?.operations?.queue||[]).filter(q=>!['skipped','cancelled'].includes(q.status)).map(q=>[q.contact_id,q]));
  const followups=new Map([...(data?.calendar?.followups||[]),...(data?.calendar?.followup_skips||[])].sort((a,b)=>(a.updated_at||'').localeCompare(b.updated_at||'')).map(f=>[f.contact_id,f]));
  const unique=new Map();
  for(const c of data?.campaigns||[]){if(c.engine!==workspace)continue;for(const a of c.accounts){for(const p of a.contacts){const id=fullId(c,a,p),q=queue.get(id),f=followups.get(id),row={id,p,a,c,q,f,status:contactStatus(p,q,f)};const key=(p.email||`${a.domain||a.name}/${p.name}`).toLowerCase();const old=unique.get(key);if(!old||(p.state?.touch_number||0)>(old.p.state?.touch_number||0)||((p.state?.touch_number||0)===(old.p.state?.touch_number||0)&&(c.mission?.created_at||'')>(old.c.mission?.created_at||'')))unique.set(key,row)}}}
  return [...unique.values()];
 },[data,workspace]);
 const inScope=rows.filter(r=>(batch==='all'||r.c.id===batch)&&(allPeople||r.p.rank===1||r.p.state?.touch_number>0));
 const counts=Object.fromEntries(Object.keys(statusLabels).map(k=>[k,k==='all'?inScope.length:inScope.filter(r=>r.status.key===k).length]));
 const visible=inScope.filter(r=>(filter==='all'||r.status.key===filter)&&(!search||`${r.p.name} ${r.p.role} ${r.p.email||''} ${r.a.name} ${r.a.industry||''}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='company'?a.a.name.localeCompare(b.a.name):(['reply','followup','draft','write','research','scheduled','waiting','held','closed'].indexOf(a.status.key)-['reply','followup','draft','write','research','scheduled','waiting','held','closed'].indexOf(b.status.key))||(a.a.opportunity?.priority??999)-(b.a.opportunity?.priority??999)||a.a.name.localeCompare(b.a.name));
 const selectedRow=visible.find(r=>r.id===selected)||visible[0];
 const latest=campaigns.filter(c=>c.counts.companies).sort((a,b)=>(b.mission?.created_at||'').localeCompare(a.mission?.created_at||''))[0];
 function choose(id){const r=rows.find(x=>x.id===id);if(!r)return;setSelected(id);setView('contacts');history.replaceState(null,'','#account/'+id);setFilter('all');setBatch('all');setSearch('');setAllPeople(true);}
 function locate(entry){choose(entry.contact_id||`${entry.campaign}/${entry.account_id}/${entry.person_id}`)}
 function navigate(next){setView(next);setSearch('');history.replaceState(null,'',`#${next==='calendar'?'schedule':next}`)}
 async function saveMission(e){e.preventDefault();setSaving(true);try{await api('/api/missions',{goal,engine:workspace});setMissionOpen(false);setGoal('');await refresh();setToast('Research request saved.')}catch(e){setToast(e.message)}finally{setSaving(false)}}
 return <div className="crm-shell">
  <aside className="crm-sidebar"><a className="crm-brand" href="#contacts" onClick={e=>{e.preventDefault();navigate('contacts')}}><b>a<span>.</span></b><span>Outreach</span></a><div className="crm-workspaces"><small>WORKSPACE</small>{Object.entries(workspaces).map(([key,name])=><button key={key} aria-pressed={workspace===key} className={workspace===key?'active':''} onClick={()=>{setWorkspace(key);setBatch('all');setFilter('all');setSelected('');setSearch('')}}><i className={key}/>{name}</button>)}</div><nav className="crm-navigation" aria-label="Main navigation">{[['contacts','Contacts','▤'],['followups','Follow-ups','↪'],['calendar','Calendar','▦']].map(([key,label,icon])=><button key={key} className={view===key?'active':''} aria-current={view===key?'page':undefined} onClick={()=>navigate(key)}><span>{icon}</span>{label}</button>)}</nav><div className="crm-sidebar-bottom"><a href="?advanced=1#analytics">Reports & advanced views ↗</a><span><i/> Local workspace</span></div></aside>
  <main className="crm-main"><header className="crm-topbar"><span>{workspaces[workspace]}<b>/</b>{view==='contacts'?'Contacts':view==='followups'?'Follow-ups':'Calendar'}</span><div><span className="crm-updated">{data?'Updated '+new Date(data.generated_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'Loading…'}</span><button aria-label="Refresh CRM" className="crm-refresh" onClick={refresh}>↻</button><button className="button secondary" onClick={()=>setMissionOpen(true)}>＋ Research request</button></div></header>
   <section className="crm-page"><div className="crm-title"><div><h1>{view==='contacts'?'Contacts':view==='followups'?'Follow-ups':'Calendar'}</h1><p>{view==='contacts'?'People, emails and the next step. All in one place.':view==='followups'?'Pick a person. Read the thread. Review the reply.':'Your planned and recorded outreach.'}</p></div>{view==='contacts'&&latest&&<button className="crm-latest" onClick={()=>{setBatch(latest.id);history.replaceState(null,'','#contacts/'+encodeURIComponent(latest.id));setFilter('all');setSearch('');setSelected('');setAllPeople(false)}}><span>Latest batch</span><strong>{latest.counts.companies} companies <b>↗</b></strong></button>}</div>
    <div className="crm-controls"><label className="crm-search"><span>⌕</span><input ref={searchRef} aria-label="Search contacts" placeholder="Search company, person or role…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></label>{view==='contacts'&&<><label className="crm-batch"><span>Batch</span><select aria-label="Contact batch" value={batch} onChange={e=>{setBatch(e.target.value);setSelected('')}}><option value="all">All batches</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="crm-all-people"><input type="checkbox" checked={allPeople} onChange={e=>setAllPeople(e.target.checked)}/> Include uncontacted backups</label></>}</div>
    {error&&<div className="error" role="alert">{error} <button onClick={refresh}>Retry</button></div>}
    {!data?<div className="crm-loading">Loading your workspace…</div>:view==='contacts'?<><div className="crm-status-filters" aria-label="Contact status">{Object.entries(statusLabels).filter(([k])=>k==='all'||counts[k]>0).map(([key,label])=><button key={key} aria-pressed={filter===key} className={filter===key?'selected':''} onClick={()=>{setFilter(key);setSelected('')}}>{label}<span>{counts[key]}</span></button>)}</div><div className="crm-results-heading"><span>{visible.length} contacts{batch!=='all'?` · ${campaigns.find(c=>c.id===batch)?.name}`:''}</span><button onClick={()=>setSort(sort==='priority'?'company':'priority')}>Sort: {sort==='priority'?'Next action':'Company'} ↕</button></div><div className={'crm-split'+(selectedRow?' has-selection':'')}><div className="crm-contact-table" role="region" aria-label="Contact list"><table><thead><tr><th>Company / person</th><th>Status / next step</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className={r.id===selectedRow?.id?'selected':''} onClick={()=>setSelected(r.id)}><td><button aria-label={`Open ${r.p.name} at ${r.a.name}`} aria-current={r.id===selectedRow?.id?'true':undefined} onClick={()=>setSelected(r.id)}><strong>{r.a.name}</strong><span>{r.p.name}</span><small>{r.p.role}</small></button></td><td><span className={'crm-status '+r.status.key}>{statusLabels[r.status.key]}</span><small>{r.status.action}</small></td></tr>)}</tbody></table>{!visible.length&&<div className="crm-no-results"><h3>No matching contacts</h3><p>Try another name or clear the filters.</p><button className="button secondary" onClick={()=>{setSearch('');setFilter('all');setBatch('all')}}>Clear filters</button></div>}</div><div className="crm-reading-pane" role="region" aria-label="Contact details"><ContactReader row={selectedRow} Email={Email} refresh={refresh} notice={setToast} onChoose={choose} onFollowup={r=>{setFollowupFocus(r.f);navigate('followups')}}/></div></div></>:view==='followups'?<Followups calendar={data.calendar} workspace={workspace} search={search} api={api} refresh={refresh} notice={setToast} openAccount={locate} focus={followupFocus}/>:<Calendar calendar={data.calendar} workspace={workspace} search={search} refresh={refresh} api={api} notice={setToast} openAccount={locate} inspect={locate}/>}
   </section>
  </main>
  <Dialog.Root open={missionOpen} onOpenChange={setMissionOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="crm-modal"><Dialog.Title>What should we research?</Dialog.Title><Dialog.Description>Describe the companies or people you want to add.</Dialog.Description><form onSubmit={saveMission}><textarea aria-label="Research request" rows={5} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Find 20 robotics companies and the engineers who own planning and reliability."/><div><Dialog.Close asChild><button type="button" className="button secondary">Cancel</button></Dialog.Close><button className="button" disabled={saving||!goal.trim()}>{saving?'Saving…':'Save request'}</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>
  {toast&&<div className="toast" role="status">{toast}</div>}
 </div>;
}
